// Generated by CoffeeScript 1.4.0
(function() {
  var paper;

  paper = Raphael("kickstarter", 300, 60);

  paper.text(50, 50, "find out more @").attr({
    fill: '#000',
    stroke: 'none'
  });

  paper.image("images/kickstarter.png", 0, 100, 20);

}).call(this);
